function w = get_w(x,y,z)
%w Summary of this function goes here
%   Detailed explanation goes here
    w = [-(sin(x - z)/(-cos(x - z) + 4.*cosh(y))) + ( ...
 sin(x - z)*(-cos(x - z) + 4.*cosh(y) + 4.*sinh(y)))/(-cos(x - z) + ...
   4.*cosh(y))^2 + ((-cos(x - z) + 4.*cosh(y) + ...
    4.*sinh(y))*(sin(x - z)/(-cos(x - z) + 4.*cosh(y)) - ( ...
    sin(x - z)*(-cos(x - z) + 4.*cosh(y) + ...
       4.*sinh(y)))/(-cos(x - z) + 4.*cosh(y))^2))/(-cos(x - z) + ...
  4.*cosh(y)) - ( ...
 sin(x - z)*((4.*cosh(y) + 4.*sinh(y))/(-cos(x - z) + 4.*cosh(y)) - ( ...
    4.*sinh(y)*(-cos(x - z) + 4.*cosh(y) + ...
       4.*sinh(y)))/(-cos(x - z) + 4.*cosh(y))^2))/(-cos(x - z) + ...
  4.*cosh(y)); cos(x - z)/(-cos(x - z) + 4.*cosh(y)) - ...
 sin(x - z)^2/(-cos(x - z) + 4.*cosh(y))^2 - ( ...
 4.*sin(x - z)^2*sinh(y))/(-cos(x - z) + ...
   4.*cosh(y))^3 + ((-(cos(x - z)/(-cos(x - z) + 4.*cosh(y))) + ...
    sin(x - z)^2/(-cos(x - z) + 4.*cosh(y))^2)*(-cos(x - z) + ...
    4.*cosh(y) + 4.*sinh(y)))/(-cos(x - z) + 4.*cosh(y)); 0];
end

